# -*- coding: utf-8 -*-
"""Chap3Ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCHrRVPkjaSs5KHiv_T-aXR6Gp-wsZo3
"""

friends = ["Arnan", "JP", "Adam"]
message = "Hello my good friend, "
print(message + friends[0])
print(message + friends[1])
print(message + friends[2])