# -*- coding: utf-8 -*-
"""Chap3Ex7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCHrRVPkjaSs5KHiv_T-aXR6Gp-wsZo3
"""

place = ["Bali", "Paris", "Bora Bora", "Siargao", "Tokyo"]
print(place)
print(" ")
print(sorted(place))
print(place)
print(" ")
print(sorted(place, reverse=True))
print(place)
print(" ")
place.reverse()
print(place)
place.reverse()
print(place)
print(" ")
place.sort()
print(place)
place.sort(reverse=True)
print(place)