# -*- coding: utf-8 -*-
"""Chap3Ex3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCHrRVPkjaSs5KHiv_T-aXR6Gp-wsZo3
"""

transpos = ["car", "metro", "bus"]
message = ("When going out with my family, we use our " + transpos[0] + ".")
message2 = ("When going out with friends, I usually go by " + transpos[1] + ".")
message3 = ("I go by " + transpos[2] + " to get to the nearest metro.")
print(message)
print(message2)
print(message3)